# ==========
# HOME
# ==========

### home
GET http://localhost:8080/

# ==========
# AUTH
# ==========

### Post auth register - register admin
POST http://localhost:8080/users/register
Content-Type: application/json

{
  "username": "admin1",
  "password1": "124",
  "password2": "124",
  "email": "admin@test.com",
  "userType": "Admin"
}

### Post auth register - register new user
POST http://localhost:8080/users/register
Content-Type: application/json

{
  "username": "userlein",
  "password1": "124",
  "password2": "124",
  "email": "example@test.com",
  "userType": "User"
}

### Post auth login - user login
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "username": "userlein",
  "password": "124"
}

###
# ==========
# USER
# ==========

### Get userlist
GET http://localhost:8080/users/

### Get user profile
GET http://localhost:8080/users/d84257ca-a326-4c78-b047-13f658abe039/profile
Authorization: Bearer userlein-mrpToken

### Put users profile - update user profile
PUT http://localhost:8080/users/d84257ca-a326-4c78-b047-13f658abe039/profile
Content-Type: application/json
Authorization: Bearer userlein-mrpToken

{
  "username": "user",
  "passwordOld": "124",
  "passwordNew1": "127",
  "passwordNew2": "127"
}

### Get user ratings
GET http://localhost:8080/users/d84257ca-a326-4c78-b047-13f658abe039/ratings
Authorization: Bearer user-mrpToken

### Get user favorites
GET http://localhost:8080/users/d84257ca-a326-4c78-b047-13f658abe039/favorites
Authorization: Bearer user-mrpToken

### Delete user
DELETE http://localhost:8080/users/d84257ca-a326-4c78-b047-13f658abe039
Authorization: Bearer user-mrpToken

# ==========
# MEDIA
# ==========

### Get media - list media entries
GET http://localhost:8080/media

### Post media - create media entry
POST http://localhost:8080/media
Content-Type: application/json
Authorization: Bearer userleini-mrpToken

{
  "title": "That best game ever",
  "description": "where you play that one person",
  "genre":["Sci-Fi", "Drama"],
  "mediaType": "GAME",
  "releaseYear": 2010,
  "ageRestriction": 5
}

### Get media id
GET http://localhost:8080/media/510a84db-ad6c-418e-a0ad-2063a0e40a50

### Put media id - Update media entry
PUT http://localhost:8080/media/06541519-d5e2-480f-9c16-fce4909b80e3
Content-Type: application/json
Authorization: Bearer userleini-mrpToken

{
  "title": "good movie"
}

### Delete media
DELETE http://localhost:8080/media/510a84db-ad6c-418e-a0ad-2063a0e40a50
Authorization: Bearer userleini-mrpToken

# ==========
# RATING
# ==========

### Get ratings
GET http://localhost:8080/ratings

### Post media rate - rate media entry
POST http://localhost:8080/media/eb3f2f43-e7df-4f19-b50e-98cc88283d3c/rate
Content-Type: application/json
Authorization: Bearer admin-mrpToken

{
  "comment": "bad from the beginning to the end",
  "stars": 1
}

### Post ratings like - like a rating
POST http://localhost:8080/ratings/fde9bae8-5d2f-44da-8c03-d3842a8c1edd/like
Authorization: Bearer admin-mrpToken

### Put ratings - update a rating
PUT http://localhost:8080/ratings/6bcf9e14-aa8e-4a9a-98a4-3e70b403a225
Content-Type: application/json
Authorization: Bearer admin-mrpToken

{
  "stars": 1
}

### Post ratings confirm - confirm rating comment
POST http://localhost:8080/ratings/fde9bae8-5d2f-44da-8c03-d3842a8c1edd/confirm
Authorization: Bearer admin-mrpToken

### Delete ratings
DELETE http://localhost:8080/ratings/fde9bae8-5d2f-44da-8c03-d3842a8c1edd
Authorization: Bearer admin-mrpToken

# ==========
# FAVORITES
# ==========

### Post media favorite - mark as favorite
POST http://localhost:8080/media/eb3f2f43-e7df-4f19-b50e-98cc88283d3c/favorite
Authorization: Bearer userleini-mrpToken

### Delete media favorite
DELETE http://localhost:8080/media/eb3f2f43-e7df-4f19-b50e-98cc88283d3c/favorite
Authorization: Bearer userleini-mrpToken

# ==========
# RECOMMENDATION
# ==========

### Get users recommendations
GET http://localhost:8080/users/ef3e67e1-9a5e-49ce-a2a7-95aa2209b295/recommendations
Authorization: Bearer userleini-mrpToken

# ==========
# LEADERBOARD
# ==========

### Get leaderboard
GET http://localhost:8080/leaderboard